development:
  adapter:  postgresql
  database: scheduler_development
  pool:     5

test:
  adapter:  postgresql
  database: scheduler_test
  pool:     5

production:
  adapter:  postgresql
  database: scheduler_production
